# Generated by Django 4.1.4 on 2022-12-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedbatch',
            name='slot',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
