# Generated by Django 4.1.4 on 2022-12-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaAPI', '0002_bookedbatch_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bookedbatch',
            name='slot',
            field=models.CharField(blank=True, choices=[('5AM-6AM', '5AM-6AM'), ('6AM-7AM', '6AM-7AM'), ('7AM-8AM', '7AM-8AM'), ('8AM-9AM', '8AM-9AM')], max_length=100, null=True),
        ),
    ]
