# Generated by Django 4.1.4 on 2022-12-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YogaAPI', '0004_alter_register_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
