# Generated by Django 4.1.4 on 2022-12-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaAPI', '0005_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('idproof', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=10, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='bookedbatch',
            name='phone',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
