# Generated by Django 4.1.4 on 2022-12-15 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YogaAPI', '0010_alter_bookedbatch_slot_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='YogaAPI.register'),
        ),
    ]
