# Generated by Django 4.1.4 on 2022-12-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YogaAPI', '0011_alter_payment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to='YogaAPI.register'),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
