# Generated by Django 4.1.4 on 2022-12-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaAPI', '0016_alter_payment_phone_alter_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(blank=True, choices=[], max_length=10, null=True),
        ),
    ]
