# Generated by Django 4.1.4 on 2022-12-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaAPI', '0017_alter_payment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(blank=True, choices=[('1234567890', '1234567890')], max_length=10, null=True),
        ),
    ]
