# Generated by Django 4.1.4 on 2022-12-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaAPI', '0019_rename_datepaid_bookedbatch_slotbooked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedbatch',
            name='phone',
            field=models.CharField(blank=True, choices=[('1234567890', '1234567890'), ('7071955971', '7071955971'), ('7071955972', '7071955972'), ('7071955973', '7071955973'), ('7071955975', '7071955975'), ('7071955977', '7071955977')], max_length=10, null=True),
        ),
    ]
